language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed chukwukaemi/udagram-api-feed:v2
  - docker tag udagram-api-user chukwukaemi/udagram-api-user:v2
  - docker tag reverseproxy chukwukaemi/reverseproxy:v4
  - docker tag udagram-frontend chukwukaemi/udagram-frontend:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chukwukaemi/udagram-api-feed:v2
  - docker push chukwukaemi/udagram-api-user:v2
  - docker push chukwukaemi/reverseproxy:v4
  - docker push chukwukaemi/udagram-frontend:v3
